// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMt6NvN2rvhr11AZNZPO8W8ScI9Sr-R8',
    appId: '1:820357106054:web:b81cc1e133d1bb028ac407',
    messagingSenderId: '820357106054',
    projectId: 'flixfelx-e1229',
    authDomain: 'flixfelx-e1229.firebaseapp.com',
    storageBucket: 'flixfelx-e1229.appspot.com',
    measurementId: 'G-PTNQCZCXYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkprSDkTbweSer7-n1LfjeOL9Dev0UhRQ',
    appId: '1:820357106054:android:06c7c7142d7613f88ac407',
    messagingSenderId: '820357106054',
    projectId: 'flixfelx-e1229',
    storageBucket: 'flixfelx-e1229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvv57v0C2-djKQXp25CpT7ypH-QamlvFw',
    appId: '1:820357106054:ios:c7a527fa9d07327a8ac407',
    messagingSenderId: '820357106054',
    projectId: 'flixfelx-e1229',
    storageBucket: 'flixfelx-e1229.appspot.com',
    iosClientId: '820357106054-oa6134vfub5gcdvlpn3ugiakhpppb7as.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvv57v0C2-djKQXp25CpT7ypH-QamlvFw',
    appId: '1:820357106054:ios:c7a527fa9d07327a8ac407',
    messagingSenderId: '820357106054',
    projectId: 'flixfelx-e1229',
    storageBucket: 'flixfelx-e1229.appspot.com',
    iosClientId: '820357106054-oa6134vfub5gcdvlpn3ugiakhpppb7as.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixflex',
  );
}
